### ISSUE TITLE
generate repository with lower case

### ISSUE THREAD

**Issue by Elias-Vandewalle** [githubtraining/github-actions-publish-to-github-packages#27]
**Describe the bug**
I was just taking this course and noticed that because my github name has uppercase characters in it, the code generated by the bot was this:
```
Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: Elias-Vandewalle/github-actions-for-packages/tic-tac-toe
        tag_with_sha: true
```
The problem is that docker doesn't accept uppercase in the 'repository' input. This exercise could be completed by changing the repository to `elias-vandewalle/github-actions-for-packages/tic-tac-toe`.

**To Reproduce**
1. Have an uppercase character in your username
2. Start the exercise
3. Rename the file, get to the step where you change the contents & name of ci-workflow.yml
4. Docker Build, Tag, Push will fail if there is an uppercase character in the repository

**Screenshots**
![image](https://user-images.githubusercontent.com/70571779/104897542-c91cfd80-5978-11eb-82d9-b5f3284cae55.png)

**Expected behavior**
generate repository in lowercase
