### ISSUE TITLE
Bug on the cd-workflow

### ISSUE THREAD

**Issue by Bigaston** [githubtraining/github-actions-publish-to-github-packages#30]
**Describe the bug**
On the Step 2, when you have to build and publish the Docker Image to Docker Package, the config is not true.

I have some problems:
- First the bot use Bigaston/... as package name (on the response), and Docker not accept uppercase so maybe it can be cool to lowercase the package name?
- Then, when I cant to publish, I've firstly an error and I see a warning so I pass the build-push-action to version 2 but at this moment the build doesn't Work
- I've to read the documentation on github and on the build-push-action repo to find what is the correct config. I've use this finaly

```
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: webpack artifacts
        path: public
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I don't really know how to update the course so I just want to report the problem here ^^' But thanks for the lesson, it's very intresting!
